const priorityMap = {
  agotado: 1,
  bajo: 2,
  "en orden": 3,
};

export const MEDICINES = [
  {
    id: 1,
    name: "metronidazol 200 ovulos ",
    totalUnit: 1,
    price: 6000,
    lastUpdate: "2026-04-10",
    status: "en orden",
    activePrinciple: "500mg",
    isMedicine: true,
  },
  {
    id: 2,
    name: "nifedipino",
    totalUnit: 10,
    price: 0,
    lastUpdate: "2026-04-10",
    status: "en orden",
    activePrinciple: "30mg",
    isMedicine: true,
  },
  {
    id: 3,
    name: "furosemida",
    totalUnit: 1,
    price: 0,
    lastUpdate: "2026-04-10",
    status: "en orden",
    activePrinciple: "40mg",
    isMedicine: true,
  },
  {
    id: 4,
    name: "acetaminofen",
    totalUnit: 1,
    price: 0,
    lastUpdate: "2026-04-10",
    status: "en orden",
    activePrinciple: "500mg",
    isMedicine: true,
  },
  {
    id: 5,
    name: "levetiracetam",
    totalUnit: 1,
    price: 0,
    lastUpdate: "2026-04-10",
    status: "en orden",
    activePrinciple: "500mg",
    isMedicine: true,
  },
  {
    id: 6,
    name: "metformina",
    totalUnit: 1,
    price: 0,
    lastUpdate: "2026-04-20",
    status: "en orden",
    activePrinciple: "500mg",
    isMedicine: true,
  },
  {
    id: 7,
    name: "ezetimibe + Rosuvastanina",
    totalUnit: 1,
    price: 0,
    lastUpdate: "2026-04-10",
    status: "en orden",
    activerinciple: "10mg/40mg",
    isMedicine: true,
  },
  {
    id: 8,
    name: "omeprazol",
    totalUnit: 1,
    price: 0,
    lastUpdate: "2026-04-20",
    status: "en orden",
    activePrinciple: "20mg",
    isMedicine: true,
  },
  {
    id: 9,
    name: "empagliflozina",
    totalUnit: 1,
    price: 0,
    lastUpdate: "2026-04-20",
    status: "en orden",
    activePrinciple: "25mg",
    isMedicine: true,
  },
  {
    id: 10,
    name: "valsartan",
    totalUnit: 1,
    price: 0,
    lastUpdate: "2026-04-20",
    status: "en orden",
    activePrinciple: "160mg",
    isMedicine: true,
  },
  {
    id: 12,
    name: "gaza alfa no tej 3x3",
    totalUnit: 10,
    price: 10000,
    lastUpdate: "2026-04-20",
    status: "en orden",
    activePrinciple: null,
    isMedicine: false,
  },
  {
    id: 13,
    name: "vaselina drogam",
    totalUnit: 1,
    price: 4900,
    lastUpdate: "2026-04-20",
    status: "en orden",
    activePrinciple: "60gr",
    isMedicine: false,
  },
  {
    id: 14,
    name: "jabon antibacterial",
    totalUnit: 1,
    price: 8000,
    lastUpdate: "2026-04-20",
    status: "en orden",
    activePrinciple: "60ml",

    isMedicine: false,
  },
  {
    id: 15,
    name: "guantex asantex protex",
    totalUnit: 1,
    price: 22000,
    lastUpdate: "2026-04-20",
    status: "en orden",
    activePrinciple: null,
    isMedicine: false,
  },
  {
    id: 16,
    name: "alcohol osa",
    totalUnit: 1,
    price: 8000,
    lastUpdate: "2026-04-20",
    status: "en orden",
    activePrinciple: "700ml",
    isMedicine: false,
  },
  {
    id: 17,
    name: "toallas win aloe+vitam.E",
    totalUnit: 1,
    price: 12500,
    lastUpdate: "2026-04-20",
    status: "en orden",
    activePrinciple: null,
    isMedicine: false,
  },
  {
    id: 18,
    name: "1 metro de fixonul",
    totalUnit: 1,
    price: 10000,
    lastUpdate: "2026-04-20",
    status: "en orden",
    activePrinciple: null,
    isMedicine: false,
  },
].sort((a, b) => {
  const diff = priorityMap[a.status] - priorityMap[b.status];

  if (diff !== 0) return diff;

  if (a.isMedicine !== b.isMedicine) return b.isMedicine - a.isMedicine;

  return a.name.localeCompare(b.name);
});

export const TOTAL_MEDICINES = MEDICINES.reduce((a, b) => a + b?.price, 0);
