### register user
POST  http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "David Sliren",
    "username": "DavidSalaza", 
    "relationship": "hijo",
    "tel": "3044518133",
    "email": "quemas12@gmail.com",
    "password": "Noseqponer12"
}

### login user

POST http://localhost:3000/api/auth/login 
Content-Type: application/json

{
    "username": "davidsalaza",
    "password": "Noseqponer12"
}

### logout user
POST http://localhost:3000/api/auth/logout 
Content-Type: application/json