### register user
POST http://localhost:3000/api/auth/sign-up/email
Content-Type: application/json

{
    "name": "David Sliren",
    "username": "jhojan12",
    "email": "correo@correo.com",
    "relationship": "hijo",
    "tel": "3044518133",
    "password": "Jojojo12"
}

### login user
POST http://localhost:3000/api/auth/sign-in/username
Content-Type: application/json

{
    "username": "sliren",
    "password": "Jojojo12"
}

### logout user
POST http://localhost:3000/api/auth/sign-out
Content-Type: application/json
