import { TanstackProvider } from "@/components/provaider/TanstackProvider";
import "./globals.css";
import { bodyFont } from "@/config/fonts";
import { ANALYTICS } from "@/constants/env";
import { GoogleAnalytics } from "@next/third-parties/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
export const metadata = {
  title: "Aleida | Contribucion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${bodyFont.variable} h-full antialiased not-scrollbar lg:scroll-hiden `}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <NuqsAdapter>
          <TanstackProvider>{children}</TanstackProvider>
        </NuqsAdapter>
      </body>
      <GoogleAnalytics gaId={ANALYTICS} />
    </html>
  );
}
